import { prisma } from '@/lib/prisma'
import { createMentor } from '@/services/mentor.service'
import { success, error } from '@/lib/api-response'

/**
 * GET /api/debug/create-mentor
 *
 * Dev-only endpoint — creates a test mentor using the FIRST user in the DB.
 * Demonstrates that prisma.mentor.create() generates a valid UUID via
 * @default(uuid()), unlike Prisma Studio which bypasses the Prisma client.
 *
 * HOW TO USE:
 *   curl http://localhost:3000/api/debug/create-mentor
 *
 * REMOVE THIS FILE before deploying to production.
 */
export async function GET() {
  if (process.env.NODE_ENV === 'production') {
    return error('Debug endpoints are disabled in production', 403)
  }

  // Find first available user to associate with the test mentor
  const user = await prisma.user.findFirst()
  if (!user) return error('No users found. Sign in with Google first, then retry.', 404)

  // Check if this user already has a mentor profile
  const existing = await prisma.mentor.findUnique({ where: { userId: user.id } })
  if (existing) {
    return success({
      message: 'User already has a mentor profile',
      mentor: existing,
      note: 'UUID was generated correctly via prisma.mentor.create()',
    })
  }

  try {
    const mentor = await createMentor({
      userId:       user.id,
      iit:          'IIT Delhi',
      branch:       'Computer Science',
      year:         3,
      languages:    ['Hindi', 'English'],
      bio:          'I cracked JEE Advanced 2023 with AIR 142. I can help you with Physics and Maths strategy, time management, and mock test review. Happy to guide serious aspirants.',
      calendlyLink: 'https://calendly.com/test-mentor/20min',
    })

    return success({
      message: '✅ Mentor created successfully. UUID generated by Prisma client.',
      mentor,
      explanation: {
        why_studio_failed: '@default(uuid()) is a Prisma CLIENT default, not a PostgreSQL default. Prisma Studio writes directly to the DB and skips client-level defaults.',
        fix: 'Always create mentors via POST /api/mentors or this debug endpoint.',
      },
    }, 201)
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Unknown error'
    return error(`Failed to create mentor: ${message}`, 500)
  }
}
